name: Deploy website to Heroku
on:
  push:
    branches:
      - master
jobs:
    deploy:
      runs-on: ubuntu-lastest
      steps:
        - uses: actions/checkout@v2
        - uses: michaelw90/PHP-Lint@master